/**
 * Curated content library.
 *
 * Everything the app can turn into a puzzle lives here as data. Images are
 * grouped into six categories; each has a full-res source (used as the puzzle
 * image) and a thumbnail (used in grids and the picker). "Live" clips are short
 * looping videos with a still poster frame for use anywhere a `<video>` element
 * shouldn't autoplay (marketing grid, picker).
 *
 * Free vs Premium: the `tier` field gates visibility. Premium is waitlist-only
 * for now (no purchase flow) — see `src/content/tiers.ts`. Flip a `tier` here to
 * move an item between tiers; add rows to grow the library toward the 30–50
 * target. `curated: true` marks assets that are real curated originals (Google
 * AI Studio stills / Morph Studio clips) rather than stand-ins.
 */
import type { ContentType } from '../game/types';

export type Tier = 'free' | 'premium';

export const CATEGORIES = [
  'Landscapes / Nature',
  'Animals / Wildlife',
  'Architecture / Cityscapes',
  'Space / Cosmic',
  'Abstract / Pattern Art',
  'Florals / Botanical',
] as const;
export type Category = (typeof CATEGORIES)[number];

export interface ImageItem {
  kind: 'image';
  key: string;
  name: string;
  category: Category;
  tier: Tier;
  curated: boolean;
  full: string;
  thumb: string;
}

export interface VideoItem {
  kind: 'video';
  key: string;
  name: string;
  tier: Tier;
  curated: boolean;
  src: string;
  poster: string;
}

export type LibraryItem = ImageItem | VideoItem;

/**
 * Placeholder assets are `.svg` (generated by `scripts/gen-placeholders.mjs`).
 * When the real curated originals land, drop them in with the same base names
 * and change `IMG_EXT` to `'jpg'` — nothing else needs to move.
 */
export const IMG_EXT: 'svg' | 'jpg' = 'jpg';

const imgFull = (key: string) =>
  `/uploads/puzzle-library/full/puz_${key}.${IMG_EXT}`;
const imgThumb = (key: string) =>
  `/uploads/puzzle-library/thumbs/puz_${key}.${IMG_EXT}`;
const poster = (key: string) =>
  `/uploads/puzzle-library/posters/poster_${key}.${IMG_EXT}`;

function image(
  key: string,
  name: string,
  category: Category,
  tier: Tier,
): ImageItem {
  return {
    kind: 'image',
    key,
    name,
    category,
    tier,
    curated: true,
    full: imgFull(key),
    thumb: imgThumb(key),
  };
}

/**
 * The 12 items confirmed in the prototype's grid, two per category. One free +
 * one premium per category gives Free "a curated selection from every category"
 * while leaving a clear upgrade path. Extend with more rows per category to
 * reach the full 30–50.
 */
export const IMAGES: ImageItem[] = [
  image('mountain-valley', 'Mountain Valley', 'Landscapes / Nature', 'free'),
  image('autumn-canopy', 'Autumn Canopy', 'Landscapes / Nature', 'premium'),
  image('fox', 'Fox', 'Animals / Wildlife', 'free'),
  image('snow-leopard', 'Snow Leopard', 'Animals / Wildlife', 'premium'),
  image('cityscape', 'Cityscape', 'Architecture / Cityscapes', 'free'),
  image('courtyard', 'Courtyard', 'Architecture / Cityscapes', 'premium'),
  image('nebula', 'Nebula', 'Space / Cosmic', 'free'),
  image('solar-sys', 'Solar System', 'Space / Cosmic', 'premium'),
  image('abstract-swirl', 'Abstract Swirl', 'Abstract / Pattern Art', 'free'),
  image('mosaic', 'Mosaic', 'Abstract / Pattern Art', 'premium'),
  image('botanicals', 'Botanicals', 'Florals / Botanical', 'free'),
  image('poppies', 'Poppies', 'Florals / Botanical', 'premium'),
];

/** The 5 confirmed Live clips. All free — Live is a Free-tier mode; Premium's
 * Live value is user uploads (not built yet). */
export const VIDEOS: VideoItem[] = [
  { kind: 'video', key: 'clouds', name: 'Clouds', tier: 'free', curated: true, src: '/uploads/clouds_2.mp4', poster: poster('clouds') },
  { kind: 'video', key: 'balloons', name: 'Balloons', tier: 'free', curated: true, src: '/uploads/balloons.mp4', poster: poster('balloons') },
  { kind: 'video', key: 'fire', name: 'Fire', tier: 'free', curated: true, src: '/uploads/fire.mp4', poster: poster('fire') },
  { kind: 'video', key: 'murmuration', name: 'Murmuration', tier: 'free', curated: true, src: '/uploads/murmuration.mp4', poster: poster('murmuration') },
  { kind: 'video', key: 'jellyfish', name: 'Jellyfish', tier: 'free', curated: true, src: '/uploads/jellyfish.mp4', poster: poster('jellyfish') },
];

export const fullSrcForKey = (key: string) => imgFull(key);
export const posterSrcForKey = (key: string) => poster(key);

export const DEFAULT_IMAGE_SRC = IMAGES[0].full; // Mountain Valley
export const DEFAULT_VIDEO_SRC = VIDEOS[1].src; // Balloons — matches the prototype default

export function imageBySrc(src: string): ImageItem | undefined {
  return IMAGES.find((i) => i.full === src);
}
export function videoBySrc(src: string): VideoItem | undefined {
  return VIDEOS.find((v) => v.src === src);
}

export function imagesByCategory(): [Category, ImageItem[]][] {
  return CATEGORIES.map((cat) => [cat, IMAGES.filter((i) => i.category === cat)]);
}

/** Label for a puzzle currently loaded from `src` (image or video). */
export function labelForSrc(contentType: ContentType, src: string): string {
  if (contentType === 'video') return videoBySrc(src)?.name ?? 'Live';
  return imageBySrc(src)?.name ?? 'Library';
}
